### ISSUE TITLE
Importing Notes entity failure

### ISSUE THREAD

**Issue by clarkac1** [eileenmcnaughton/nz.co.fuzion.csvimport#28]
Using this facility to import notes is very useful, as the standard import only allows the note itself and no other associated fields.  However (although I did get it to work just once) all note updates are rejected with the error 'contact id is not a valid integer' (even though it is, of course). See screenshot for error. They are rejected with or without 'Allow Updating An Entity Using Unique Fields' being checked.  id was the external id, but also tried with contact id and this failed in the same way.
![screenshot_20190412_142640](https://user-images.githubusercontent.com/5676413/56040995-953a9000-5d2f-11e9-9bb1-f3939a570fea.png)

**Comment by clarkac1** [comment]
Using Civi 5.11 with API 4 extension

**Comment by vinuvarshith** [comment]
@clarkac1 can you also share the mappings you used with a sample row?

**Comment by clarkac1** [comment]
Here's a sample row 
[Civitest.zip](https://github.com/eileenmcnaughton/nz.co.fuzion.csvimport/files/3074857/Civitest.zip)
and here's a screenshot of the mapping in the database
![screenshot_20190412_202550](https://user-images.githubusercontent.com/5676413/56061428-50c7e800-5d61-11e9-84a5-751712c14d45.png)

**Comment by Stoob** [comment]
I can confirm this Notes import error @clarkac1 and @eileenmcnaughton and add the following debugging information:

`Error: Class name must be a valid object or a string in civicrm_api3_generic_getunique() (line 28 of /home/centos/public_html/sites/all/modules/civicrm/api/v3/Generic/Getunique.php)`

**Comment by masetto** [comment]
Hi, has anyone found a hack to bypass the problem?

**Comment by mariav0** [comment]
I can also confirm this error:

`PHP Fatal error:  Uncaught Error: Class name must be a valid object or a string in /html/wordpress/wp-content/plugins/civicrm/civicrm/api/v3/Generic/Getunique.php:28`

CiviCRM 5.59.4

**Comment by eileenmcnaughton** [comment]
The class signature issue appears to have been included in the latest tagged release
