### ISSUE TITLE
Expecting to upgrade to 4.6/4.7?

### ISSUE THREAD

**Issue by JoeMurray** [eileenmcnaughton/nz.co.fuzion.csvimport#3]
We haven't used this extension but it seems like a good approach. Do you still use this for importing or do you have a different approach these days? If you use this, are you expecting to upgrade to support more recent versions of CiviCRM?

**Comment by eileenmcnaughton** [comment]
I haven't reviewed this for a while - but I don't think any 4.6 / 4.7 changes should affect it. Saurabh is looking to do some more work on importing in GSOC with a view to making it work with other sources

**Comment by kenwest** [comment]
I'm using it in 4.7 to import Relationships, and it's working well

**Comment by eileenmcnaughton** [comment]
I've acknowledged those versions now & dropped a release
