### ISSUE TITLE
Progress bar and silent failures?

### ISSUE THREAD

**Issue by Stoob** [eileenmcnaughton/nz.co.fuzion.csvimport#31]
Initially I thought it was an External Identifier problem, but I'm noticing some confusing behavior whereby the progress bar progresses (or doesn't) irrespective of the progress bar or entity ID number changing or not.  For example, some rows may be failing on a mismatch or duplicate, but I couldn't tell.  The progress bar proceeds anyway.  In the end, there no error report generated.  Maybe just an explanation would help.  I could help write some documentation.

**Comment by Stoob** [comment]
Let me offer some screenshots and specific examples.  I'm attempting to import 400 relationships.  Turns out, when I use the CiviCRM native importer I had 4 mismatched contact types (Org/Ind).  The import completes and gives me the file attached.

But using the API importer the number (#3) is stalled out yet the progress bar is continuing after 2 minutes.  Meanwhile zero relationships are actually getting created.  And at the 15 minute mark, still zero relationships have been created, and the progress bar stalls out entirely.

![im](https://user-images.githubusercontent.com/1683473/79796346-4217f780-830a-11ea-93db-7cb16105eb46.png)
![15min](https://user-images.githubusercontent.com/1683473/79796348-42b08e00-830a-11ea-8f77-bf5d4919315f.png)
![2min](https://user-images.githubusercontent.com/1683473/79796350-42b08e00-830a-11ea-8e39-2858fccc1cb5.png)

**Comment by bph** [comment]
I had a similar experience of an import progress stalling after 32 - on a csv file with 400. CiviCRM log doesn't have any additional information.

**Comment by Stoob** [comment]
This no longer seems to be an issue, or at least we are able to skip past the apparent error with the arrow button - has it been fixed @eileenmcnaughton ?

**Comment by eileenmcnaughton** [comment]
hmm if it hasn't been hit in a year then maybe it has
