### ISSUE TITLE
repetitive field names

### ISSUE THREAD

**Issue by michaelmcandrew** [eileenmcnaughton/nz.co.fuzion.csvimport#37]
hey @eileenmcnaughton 

we have a custom data structure for a site where a lot of contact subtypes have their own field called Type, which results in a confusing UI. Prefixing those fields with their custom group name would help disambiguate but I from a quick look at the code, I was not sure how those labels were getting populated. Any chance you could point me in the right direction? Something close to this line, I guess? https://github.com/eileenmcnaughton/nz.co.fuzion.csvimport/blob/master/CRM/Csvimport/Import/Form/MapFieldBaseClass.php#L83

![image](https://user-images.githubusercontent.com/209967/126175575-2405fea2-f53c-4d66-bfb6-4ca5e335742a.png)

**Comment by eileenmcnaughton** [comment]
Perhaps in this function https://github.com/eileenmcnaughton/nz.co.fuzion.csvimport/blob/36d72880c2cea2e147b72b398eb4c7a6dacee222/CRM/Csvimport/Task/Import.php#L16

**Comment by michaelmcandrew** [comment]
@eileenmcnaughton - that didn't work, I am afraid. From the looks of things, the list comes ready made on this line: https://github.com/eileenmcnaughton/nz.co.fuzion.csvimport/blob/master/CRM/Csvimport/Import/Form/MapFieldBaseClass.php#L83

But where `$this->get('fields');` gets its data from is a mystery to me. Do you have any thoughts on how I might be able to work that out?

**Comment by eileenmcnaughton** [comment]
@michaelmcandrew there will be a `$this->set('fields') ` somewhere that is saving it - that is a way of passing stuff between forms in a flow. The theory I believe is that it is more efficient than recalculating. But, with caching, that seems incorrect and it just adds confusion. I think the 'set' values are saved as part of the form in civicrm_cache

**Comment by michaelmcandrew** [comment]
Thanks @eileenmcnaughton - that was the missing piece of info I needed!

I was adding breakpoints in my debugger assuming that the mapping would be calculated on the page load but it is set as part of during the postProcess of the previous page (`CRM_Csvimport_Import_Form_DataSource->postProcess`) and stored.

Here is a PR: https://github.com/eileenmcnaughton/nz.co.fuzion.csvimport/pull/38
