### ISSUE TITLE
Field mapping does not work?

### ISSUE THREAD

**Issue by edward-peters** [eileenmcnaughton/nz.co.fuzion.csvimport#46]
I have used this wonderful extension many times before, but when I installed the latest version 1.7 on my CiviCRM 5.49 and Drupal 9.3.6 site, the mappings option does not appear at all. Does anyone know if this is a known issue?

**Comment by edward-peters** [comment]
Oh @eileenmcnaughton you are amazing! Thank you for your quick response. Shall I then hang on for a week or two - or is it likely to be a few months?

**Comment by eileenmcnaughton** [comment]
Probably a week or 2 - although I might target 5.50 since that will be out on Wed

**Comment by andyburnsco** [comment]
@edward-peters is this what you see?

![image](https://user-images.githubusercontent.com/18341942/171505919-a1f19aa2-5d1e-4e90-9835-6b8de99b524b.png)

On Civi 5.50.0

**Comment by eileenmcnaughton** [comment]
I just pushed out .8 - which works for me on 5.49 - working on 5.50  - that will be an extra release

**Comment by edward-peters** [comment]
@eileenmcnaughton This is absolutely wonderful. Big thanks for doing this so quickly. Now I see the mappings fine on 5.49.2.

**Comment by eileenmcnaughton** [comment]
Yay - I'll close this then - it will need more fixes in 5.51 - but it looks like it's OK for another month :-)

Out of interest - what do you use it for (thinking about the core imports at the moment & thought I should ask)

**Comment by andyburnsco** [comment]
@eileenmcnaughton I do see improvements to core import occurring so I will definitely check out and test where possible! Very exciting :) We have had to write scripts for inserting / updating directly to MySQL to get around Civi limitations of large imports. Been looking at https://lab.civicrm.org/extensions/advimport but had failures on initial test that I've not been able to resume.

From my experience, I use API CSV import to:

- Run large contact imports (set the "Number Of Items To Process For Each Queue Item" aka "queue runner") to a reasonable amount so this gets around time out issue and stays under max_execution_time for each "queue run.
- Inserting / updating non-contact entities like events / civicampaigns / groups, etc.

**Comment by andyburnsco** [comment]
Seeing this on mapping, though the import did work:

![image](https://user-images.githubusercontent.com/18341942/172463876-5ec011a6-d9a7-4b29-ac68-455aa16a5f62.png)

**Comment by eileenmcnaughton** [comment]
I've fixed this now - however the fix was basically 'rewrite csvimport to work with 5.51' I think we can assume something else will be broken at this stage

https://github.com/eileenmcnaughton/nz.co.fuzion.csvimport/commit/22607a49d457de7252baeab938680661e19cba82
