### ISSUE TITLE
Crashes on civi 5.59

### ISSUE THREAD

**Issue by demeritcowboy** [eileenmcnaughton/nz.co.fuzion.csvimport#56]
Just selecting api csv import from the civi menu crashes with a type error:

```
    Notice: Undefined index: entity in CRM_Core_BAO_UserJob::getTypeValue() (line 194 of .../CRM/Core/BAO/UserJob.php).
    TypeError: Return value of CRM_Import_Forms::getBaseEntity() must be of the type string, null returned in CRM_Import_Forms->getBaseEntity() (line 772 of .../CRM/Import/Forms.php).

CRM_Import_Forms->getBaseEntity() (Line: 72)
CRM_Import_Form_DataSource->buildQuickForm() (Line: 132)
CRM_Csvimport_Import_Form_DataSource->buildQuickForm() (Line: 689)
```

I guess it's expecting a userjob to exist?

What I was really trying to do was confirm that activity import problems weren't site-specific, since it doesn't seem to work anymore in 5.56, but then this came up.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy I added that function

**Comment by demeritcowboy** [comment]
Still crashes with same error.

**Comment by demeritcowboy** [comment]
I'm guessing the problem is before submitting the first page you haven't selected the entity yet, so there is no entity to return, unlike with e.g. regular contact import where you already know it's Contact.

**Comment by demeritcowboy** [comment]
This seems fixed with some recent commits.

**Comment by eileenmcnaughton** [comment]
@demeritcowboy yeah - old news....

![image](https://user-images.githubusercontent.com/336308/217074189-0a909d27-3d3d-4390-b26c-07ec205f2fbb.png)

**Comment by demeritcowboy** [comment]
It's both encouraging and sad to see even github has goofy bugs.
