### ISSUE TITLE
Loading a saved field mapping does not work anymore

### ISSUE THREAD

**Issue by demeritcowboy** [eileenmcnaughton/nz.co.fuzion.csvimport#58]
This commit https://github.com/eileenmcnaughton/nz.co.fuzion.csvimport/commit/12331a64da454dc2e8816c0d293c9a6d3d13b8ef  removed the $mappingName variable that is used lower down in that function to set the form defaults. The mapping itself saves to the db ok, and initially loads fine, but the form defaults no longer get set.

I get the impression the idea is to move to a different method, but at the moment you can't use saved mappings.

**Comment by bmango** [comment]
Just as a use case example, we do an import which maps 700+ custom fields so this feature is important for us.

**Comment by eileenmcnaughton** [comment]
I think I have fixed this in master - however, I have only tested master on 5.59 rc & am unsure if it works on 5.58 or any earlier versions of CiviCRM

**Comment by demeritcowboy** [comment]
Thanks @eileenmcnaughton. I get some warnings but looks like a separate issue (core doesn't have whatever [this is](https://github.com/civicrm/civicrm-core/blob/fa9f8051013dd6cf1e273e92c3a73854f15819e4/CRM/Import/Parser.php#L1720-L1724) for activity-contact fields). It works now. If anybody wants a quickfix for older versions it looks like what I did was this:

```patch
--- CRM/Csvimport/Import/Form/MapField.php.orig 2023-01-05 22:41:25.674010449 +0000
+++ CRM/Csvimport/Import/Form/MapField.php      2023-01-13 04:03:58.868856477 +0000
@@ -85,6 +85,11 @@
    * @access public
    */
   public function buildQuickForm() {
+    $savedMapping = $this->getSubmittedValue('savedMapping');
+    if ($savedMapping) {
+      [$mappingName] = CRM_Core_BAO_Mapping::getMappingFields($savedMapping);
+      $mappingName = $mappingName[1];
+    }

     $this->addSavedMappingFields();
     $defaults = [];
```

**Comment by eileenmcnaughton** [comment]
@demeritcowboy thanks - what was the older version you tried on (I will tag a release but not sure what version to tag against - default is 5.59 which is what I tested against)

**Comment by demeritcowboy** [comment]
I didn't try the latest code on the older site (5.56) since my hack was already in place.

**Comment by eileenmcnaughton** [comment]
thanks @bmango - I'll tag a release against that version then
