### ISSUE TITLE
Can save import mapping but can't select one

### ISSUE THREAD

**Issue by axon-obriend** [eileenmcnaughton/nz.co.fuzion.csvimport#6]
The option to "Load Saved Field Mapping" is missing from the first screen, but you have the option to save one on the field mapping screen.

**Comment by eileenmcnaughton** [comment]
I had a crack at this & I was able to load the mapping.... (tested on 4.7)

![screenshot 2016-06-11 10 11 52](https://cloud.githubusercontent.com/assets/336308/15986442/f70925f6-2fbc-11e6-8610-47c514877c03.png)

**Comment by JoeMurray** [comment]
Seems like working in 4.7, so issue should be closed pending further details from @axon-obriend
