### ISSUE TITLE
Missing Entity select field

### ISSUE THREAD

**Issue by savionlee** [eileenmcnaughton/nz.co.fuzion.csvimport#71]
I'm missing the entity select field. Another person in chat found it on drupal. https://chat.civicrm.org/civicrm/pl/sw55rjmqktn5tyxsjpbutea63c
Civi 5.76.1, csv_import 1.13, wordpress 6.6.1
![image](https://github.com/user-attachments/assets/7a657a86-61a6-4cd6-98f6-d4604f52eca0)

ConfigAndLog Error
```
2024-08-20 11:47:12-0500  [warning] entity parameter expected, always passed in core & few outside core uses so this will go Caller: CRM_Csvimport_Import_Controller::__construct
Array
(
    [civi.tag] => deprecated
)
```

PHP Error
```
[Tue Aug 20 11:47:14.973254 2024] [proxy_fcgi:error] AH01071: Got error 'PHP message: PHP Warning:  Undefined variable $contactType in /bitnami/wordpress/wp-content/plugins/civicrm/civicrm/CRM/Contact/Page/AJAX.php on line 406', ....
```

**Comment by Levi-70** [comment]
This happened with a recent update.
the issue is on Drupal as well.
I tested on dmaster demo site 5.78.alpha1
it also happens on my site which is currently on 5.76.1 it was ok when using 5.74.4.
The first time I noticed it is after upgrading from 5.74.4 to 5.76.1 so somewhere btw those civi versions

**Comment by savionlee** [comment]
There's something happening by the time `getHookedTemplateFileName()` in Core QuickForms that is picking up the normal import template instead of the extension's template on newer civi.

here's some rough screenshots, see line 114 for the different templateFile
working template call, civi 5.74.5
![working_template-call-2](https://github.com/user-attachments/assets/4895677c-5fb8-4813-b6de-f108ce5bd523)


not working template call, civi 5.76.1
![broken_template-call-2](https://github.com/user-attachments/assets/ce69e5ed-4d43-41f0-941d-04eaf7b92cfe)

**Comment by savionlee** [comment]
> There's something happening by the time `getHookedTemplateFileName()` in Core QuickForms that is picking up the normal import template instead of the extension's template on newer civi.
> 
> here's some rough screenshots, see line 114 for the different templateFile
> working template call, civi 5.74.5
> ![working_template-call-2](https://github.com/user-attachments/assets/4895677c-5fb8-4813-b6de-f108ce5bd523)
> 
> 
> not working template call, civi 5.76.1
> ![broken_template-call-2](https://github.com/user-attachments/assets/ce69e5ed-4d43-41f0-941d-04eaf7b92cfe)
> 

I need to check how that `$page` attribute is being passed in. The not working shows its calling the core import instead of csvimport a couple lines before the render template
