### ISSUE TITLE
Once the Entity Type has been chosen, is it possible to then provide 'saved mappings'

### ISSUE THREAD

**Issue by petednz** [eileenmcnaughton/nz.co.fuzion.csvimport#9]
Just spotted that while on screen 2 we can 'save a mapping' eg for ContributionRecur, when we then go back to a new import and select ContributionRecur there is no facility to 'select saved mapping'

**Comment by petednz** [comment]
Might have helped if my second import had been on the same db. apologies

**Comment by eileenmcnaughton** [comment]
:-)
